### ISSUE TITLE
Get Calendar-Availability working

### ISSUE THREAD

**Issue by stevenroh** [pixmin/Calendar-Availability#1]
Hello,
Could you say me if this project is always working ? 

I currently have problems to make it work. 
Calendar does never updates itself  (**Last update 01:00 Thursday 1st Jan 1970**).

I'm using "basic" in URL because I cannot get "full" calendar. Access not allowed :

**Forbidden**
_Error 403_

**EDIT** : Maybe that (API v2 deprecated), https://developers.google.com/google-apps/calendar/v2/developers_guide_protocol

Thanks in advance.
Greetings

**Comment by pixmin** [comment]
Indeed, "full" is not working anymore, you need to use "basic" instead. I'm going to check how to get around this.
